sudo: requiered
language: generic
services:
  - docker

before_install:
  - docker build -t andreiwke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreiwke/docker-react npm run test